# Generated by Django 4.0.5 on 2022-07-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
