# Generated by Django 4.0.5 on 2022-06-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='photo',
        ),
    ]
