# Generated by Django 4.0.5 on 2022-07-26 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0004_alter_executor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+375\\d{9}$')]),
        ),
    ]
